### ISSUE TITLE
Sonarr support broken after upgrade to latest version of HTPC Manager

### ISSUE THREAD

**Issue by bixtool** [styxit/HTPC-Manager#349]
HTPC Manager Log:

2015-04-14 22:50:42 :: modules.sonarr :: ERROR :: Failed to fetch url=http://localhost:8989/sonarr/api/profile path=profile error No JSON object could be decoded
2015-04-14 22:50:42 :: modules.sonarr :: ERROR :: Failed to fetch url=http://localhost:8989/sonarr/api/Rootfolder path=Rootfolder error No JSON object could be decoded
2015-04-14 22:50:42 :: cherrypy.error.26640112 :: ERROR :: [14/Apr/2015:22:50:42] HTTP Traceback (most recent call last):
  File "c:\HTPCManager\libs\cherrypy\_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "c:\HTPCManager\libs\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\HTPCManager\libs\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "c:\HTPCManager\libs\cherrypy\_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\HTPCManager\modules\sonarr.py", line 117, in Rootfolder
    return [folder["path"] for folder in self.fetch('Rootfolder')]
TypeError: 'NoneType' object is not iterable

2015-04-14 22:50:43 :: modules.sonarr :: ERROR :: Failed to fetch url=http://localhost:8989/sonarr/api/Series path=Series error No JSON object could be decoded
2015-04-14 22:50:43 :: modules.sonarr :: ERROR :: Failed to fetch url=http://localhost:8989/sonarr/api/History?page=1&pageSize=100&sortKey=date&sortDir=desc path=History?page=1&pageSize=100&sortKey=date&sortDir=desc error No JSON object could be decoded
2015-04-14 22:50:43 :: modules.sonarr :: ERROR :: Failed to fetch url=http://localhost:8989/sonarr/api/

**Comment by Hellowlol** [comment]
Hi. This repo don't  have sonarr. 

Can you read the issue guidelines and open a issue here https://github.com/Hellowlol/HTPC-Manager? There hasn't been any updates in sonarr for some time so it shouldn't be related to the latest update.
