### ISSUE TITLE
urllib3/pyopenssl no longer supports OpenSSL.SSL.SSLv3

### ISSUE THREAD

**Issue by duckduckquack** [styxit/HTPC-Manager#370]
[Debian no longer compiles OpenSSL with SSLv3 support](https://launchpad.net/debian/+source/openssl/1.0.1j-1).  urllib3 assumes SSLv3 support is there and fails; I have tried different requests versions, and removing/re-adding pyopenssl, but the problem still exists...

The problem appears to me that uTorrent is the cause, which I don't even use, is there a way to tell HTPC-Manager to just ignore it? Is there a place for a config file that i can set?

    python Htpc.py
2016-01-25 12:51:53 :: root :: INFO :: Welcome to HTPC-Manager!
   2016-01-25 12:51:53 :: root :: INFO :: Loglevel set to info
   2016-01-25 12:51:53 :: htpc.updater :: INFO :: Using GitUpdater engine
   2016-01-25 12:51:53 :: modules.xbmc :: WARNING :: No configured XBMC-Servers.
   Traceback (most recent call last):
     File "Htpc.py", line 189, in <module>
       main()
     File "Htpc.py", line 135, in main
       load_modules()
     File "Htpc.py", line 72, in load_modules
       from modules.utorrent import UTorrent
     File "/nas/opt/htpc-manager/modules/utorrent.py", line 4, in <module>
       import requests
     File "/nas/opt/htpc-manager/libs/requests/__init__.py", line 53, in <module>
       from requests.packages.urllib3.contrib import pyopenssl
     File "/nas/opt/htpc-manager/libs/requests/packages/urllib3/contrib/pyopenssl.py", line 42, in    <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by Hellowlol** [comment]
You need replace the libs/request folder with a newer version (above 2.6) or you can use my fork.

**Comment by duckduckquack** [comment]
is there something newer? 2.9.1 is the newest i could find.. 

pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires:

**Comment by Hellowlol** [comment]
Just grab the latest. It was fixed 2.6 that why I mentioned that version.

**Comment by duckduckquack** [comment]
Yes, I assumed it used the system version, I simply symlinked libs/requests to /usr/local/lib/python2.7/dist-packages/requests

That did the trick... thanks for your help!

**Comment by Hellowlol** [comment]
Awesome. I'm happy to help.
